### ISSUE TITLE
Default parameter not correctly set?

### ISSUE THREAD

**Issue by moooeeeep** [ros-navigation/navigation2#4316]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22.04
- ROS2 Version:
  - humble
- Version or commit hash:
  - 1.1.14-1jammy.20240407.041637
- DDS implementation:
  - rmw_fastrtps_cpp

#### Steps to reproduce issue

Install deps
```
sudo apt-get install ros-humble-turtlebot3-gazebo ros-humble-rtabmap-ros ros-humble-navigation2
```

Prepare env
```
source /opt/ros/humble/setup.bash
export ROS_LOCALHOST_ONLY=1
export TURTLEBOT3_MODEL=waffle
```

Run this launch file:
```
<launch>

  <include
      file="$(find-pkg-share turtlebot3_gazebo)/launch/turtlebot3_world.launch.py"
      />

  <include
      file="$(find-pkg-share rtabmap_demos)/launch/turtlebot3_scan.launch.py"
      />

  <include
      file="$(find-pkg-share nav2_bringup)/launch/navigation_launch.py"
      >
    <arg name="use_sim_time" value="true" />
  </include>

</launch>
```

#### Expected behavior

Gazebo Turtlebot3 Simulation, RTAB-Map SLAM and nav2 Navigation Stack is started.

#### Actual behavior

Gazebo and RTAB-Map GUI open, but full stack crashes.

Text output: 
```
[INFO] [launch]: All log files can be found below /home/dfki.uni-bremen.de/fmueller/.ros/log/2024-05-08-14-17-09-108819-HDP-MASTER-U-12655
[INFO] [launch]: Default logging verbosity is set to INFO
urdf_file_name : turtlebot3_waffle.urdf
urdf_file_name : turtlebot3_waffle.urdf
urdf_file_name : turtlebot3_waffle.urdf
[ERROR] [launch]: Caught exception in launch (see debug for traceback): [Errno 2] No such file or directory: ''
```

#### Additional information

The same launch file works without changes as expected on foxy.

If we adjust the launch file slightly to specify the `params_file` argument, it launches as expected with humble (not tested with foxy though):
```
<launch>

  <include
      file="$(find-pkg-share turtlebot3_gazebo)/launch/turtlebot3_world.launch.py"
      />

  <include
      file="$(find-pkg-share rtabmap_demos)/launch/turtlebot3_scan.launch.py"
      />

  <include
      file="$(find-pkg-share nav2_bringup)/launch/navigation_launch.py"
      >
    <arg name="use_sim_time" value="true" />
    <arg name="params_file" value="$(find-pkg-share nav2_bringup)/params/nav2_params.yaml" />
  </include>

</launch>
```

I have made a post about this here: https://robotics.stackexchange.com/questions/109897

**Comment by SteveMacenski** [comment]
I'll be honest, Foxy is so ancient and so many thousands of things have changed since then, I won't even speculate as to why a break from Foxy to Humble occurred. Foxy is legit so out of date that we stopped supporting it years before it went EOL since the project moved past ABI/API stable updates so rapidly. Things have slowed down now so its not nearly as bad, but just important context.

But, I did test

```
ros2 launch nav2_bringup navigation_launch.py
```

and that seems to work fine for me with humble binaries. Can you test as well and let me know what you see? Perhaps this is an XML launch bug.

**Comment by moooeeeep** [comment]
I agree that most serious users will probably override these parameters, but e.g., for getting started or quick tests the default config works just fine.

I just found [this other post](https://robotics.stackexchange.com/questions/107178) that seems to indicate this is indeed a more general issue, maybe a regression with `launch_ros`. I'll try to reproduce this with a more minimal setup and consider to file an issue there instead.

Thanks for your input!
