### ISSUE TITLE
Hi, I am building the package of nav2_waypoint_follower and facing that errors, 

### ISSUE THREAD

**Issue by Muteeb125** [ros-navigation/navigation2#4343]
Starting >>> nav2_waypoint_follower
--- stderr: nav2_waypoint_follower                              
/usr/bin/ld: ../libwaypoint_follower_core.so: undefined reference to `rosidl_action_type_support_t const* rosidl_typesupport_cpp::get_action_type_support_handle<nav2_msgs::action::FollowGPSWaypoints>()'
/usr/bin/ld: ../libwaypoint_follower_core.so: undefined reference to `nav2_util::setSoftRealTimePriority()'
collect2: error: ld returned 1 exit status
gmake[2]: *** [test/CMakeFiles/test_dynamic_parameters.dir/build.make:857: test/test_dynamic_parameters] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:345: test/CMakeFiles/test_dynamic_parameters.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: libwaypoint_follower_core.so: undefined reference to `rosidl_action_type_support_t const* rosidl_typesupport_cpp::get_action_type_support_handle<nav2_msgs::action::FollowGPSWaypoints>()'
/usr/bin/ld: libwaypoint_follower_core.so: undefined reference to `nav2_util::setSoftRealTimePriority()'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/waypoint_follower.dir/build.make:855: waypoint_follower] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:182: CMakeFiles/waypoint_follower.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< nav2_waypoint_follower [0.84s, exited with code 2]
Summary: 9 packages finished [3.33s]
  1 package failed: nav2_waypoint_follower
  1 package had stderr output: nav2_waypoint_follower

![Screenshot from 2024-05-15 15-37-35](https://github.com/ros-navigation/navigation2/assets/62845671/c0975772-db60-4da8-aeb2-ac11a588a13c)

**Comment by padhupradheep** [comment]
Hey, could you please fill in the template that was given? We mainly require the Distro and the Nav2 version that you are using.

**Comment by SteveMacenski** [comment]
Please reopen filling in the template properly with the relevant information.
