### ISSUE TITLE
MPPI cannot follow global path accurately

### ISSUE THREAD

**Issue by wdxairforce** [ros-navigation/navigation2#4354]
I'm currently using mppi controller nav2 in a differential robot. It work pretty well in the simulation, but when I try it in my physics robot, it look like that the robot cannot follow the path accurately, since the angular velocity of mppi output is too small to turn sharply.

I use ROS-humble, ubuntu22.04.

This link includes more detail about my question: 
[https://robotics.stackexchange.com/questions/111329/mppi-cannot-follow-path-accurately?noredirect=1#comment47516_111329](url)

**Comment by SteveMacenski** [comment]
Do not cross post with robotics stack exchange, closing.
