### ISSUE TITLE
Laser Scan rotates with robot ------- [ERROR] [1716697697.080277840] [rviz2]: Lookup would require extrapolation into the future.  Requested time 1716697697.040514 but the latest data is at time 1716697697.039929, when looking up transform from frame [laser_frame] to frame [odom]

### ISSUE THREAD

**Issue by jainvrushabh5** [ros-navigation/navigation2#4369]
## Bug report

**Required Info:**

- Operating System: Ubuntu 22.04 LTS
  - 
- ROS2 Version: ROS2 Humble

The LaserScan rotating with robot when I use teleop_twist_keyboard to manually rotate the robot. I am using the rplidar_ros package to run the lidar  I am unable to perform navigation and mapping I tried mapping 
[Screencast from 05-14-2024 01:27:45 PM.webm](https://github.com/ros-navigation/navigation2/assets/118986898/5f2a272e-8178-4362-898f-9c12189c02c0)

Map when lidar frame is rotating with robot
![pg_map](https://github.com/ros-navigation/navigation2/assets/118986898/c22bd6a6-41f8-4004-84d1-425d49708268)

Tf tree 

[frames_2024-05-26_00.17.45.pdf](https://github.com/ros-navigation/navigation2/files/15446145/frames_2024-05-26_00.17.45.pdf)

**Comment by SteveMacenski** [comment]
Ask on robotics stack exchange
