### ISSUE TITLE
Changing the params file

### ISSUE THREAD

**Issue by lesu0330** [ros-navigation/navigation2#4374]
I wish to change the nav2_params.yaml file and launch navigation_launch.py. How would I do this? I have cloned the repo and built it in ubuntu after I changed the params value. However, I get an error when I try to run it using command ros2 launch nav2_bringup navigation_launch.py use_sim_time:=false.

**Comment by padhupradheep** [comment]
Hey, we request you to fill the issue template properly. 

Please also post the relevant errors that you see in your description, so that we can help you further.
