### ISSUE TITLE
Nav2 Docking: Optional Collision Checking on undocking / docking

### ISSUE THREAD

**Issue by SteveMacenski** [ros-navigation/navigation2#4404]
Should be straight forward: check the future trajectory from the graceful controller for collisions, ignoring within some tolerance of the dock itself (since we're making or in contact there). We can use the costmap collision topic object from the costmap package analog to the Behavior Server's use.

**Comment by ajtudela** [comment]
Assign me this as it is the same behavior mentioned here: https://github.com/open-navigation/opennav_docking/pull/43. I can do both at the same time.

**Comment by SteveMacenski** [comment]
Lets add this in a separate PR containing just this work though, don't want to have franken-PRs that are too large to review / merge. Smaller bite sized pieces are always better. Then that can be used in your work. Might make sense for this to be an independent module used by the controller or something so that it can be unit-tested and deployed elsewhere as needed easily

**Comment by SteveMacenski** [comment]
Merging imminent, thanks @ajtudela this is a great feature!
