### ISSUE TITLE
Nav2 Docking: Option for Non-Charging Dock Plugin Types

### ISSUE THREAD

**Issue by SteveMacenski** [ros-navigation/navigation2#4405]
If you want to "dock" with a non-charging type, we can easily add in a new plugin type for a non-charging docking maneuver. For example: docking with a convey belt or another robot.

It should be straight forward: have a non-charging dock plugin type and adjust the logic that if we're a non-charging dock to bypass certain parts of the process. We just rely more heavily on user-defined plugin for the specific situation to understand when "done" is _done_ (though the tolerance is a pretty good and reliable metric as we found in docking even without the joint state motor efforts)

**Comment by redvinaa** [comment]
Summing up #44:
How to implement a scenario where a robot has to dock both forward and backward (for example, forward to a table / conveyor belt, and backward to actually charge)?
An option is to run two docking_server instances.

**Comment by SteveMacenski** [comment]
^ Or have the option for reversing to be a feature of the dock not of the system like we have today. Food for thought.

**Comment by SteveMacenski** [comment]
In progress - should have a PR opened this week

**Comment by SteveMacenski** [comment]
https://github.com/ros-navigation/navigation2/pull/4627 implements
