### ISSUE TITLE
Problem with bt_navigator on Humble

### ISSUE THREAD

**Issue by aleksmalm1** [ros-navigation/navigation2#4410]
Hello! I am just making sure i understand it right. I am following nav2 tutorial and i am doing `ros2 launch nav2_gps_waypoint_follower_demo gps_waypoint_follower.launch.py use_rviz:=True
`.
I am getting following error.
`[bt_navigator-14] [INFO] [1717968840.779979335] [bt_navigator]: Configuring
[bt_navigator-14] [ERROR] [1717968840.816627150] [bt_navigator]: Caught exception in callback for transition 10
[bt_navigator-14] [ERROR] [1717968840.816694406] [bt_navigator]: Original error: Could not load library: libnav2_are_error_codes_active_condition_bt_node.so: cannot open shared object file: No such file or directory
[bt_navigator-14] [WARN] [1717968840.816734050] [bt_navigator]: Error occurred while doing error handling.
[bt_navigator-14] [FATAL] [1717968840.816753154] [bt_navigator]: Lifecycle node bt_navigator does not have error state implemented
[lifecycle_manager-17] [ERROR] [1717968840.817659359] [lifecycle_manager_navigation]: Failed to change state for node: bt_navigator
[lifecycle_manager-17] [ERROR] [1717968840.817710349] [lifecycle_manager_navigation]: Failed to bring up all requested nodes. Aborting bringup.
[gzclient-2] terminate called after throwing an instance of 'gazebo::common::Exception'
[ERROR] [gzclient-2]: process has died [pid 50086, exit code -6, cmd 'gzclient'].
`
I am using ros2 humble, i got it working with Iron, but other parts of robot need humble. My question is can i make it work with humble?

**Comment by SteveMacenski** [comment]
Make sure to use the appropriate configuration files for the appropriate distributions. Things change between humble-iron-jazzy and you need to make sure you're updating your parameters or basing it on the `nav2_bringup` params for your matched distribution. 

> libnav2_are_error_codes_active_condition_bt_node.so

The error codes capably doesn't exist in Humble, its in Iron and newer. Remove those BT nodes from your configurations.
