### ISSUE TITLE
Rviz tool to get the cost of a costmap cell

### ISSUE THREAD

**Issue by tonynajjar** [ros-navigation/navigation2#4412]
#### Feature description

Sometimes when debugging planners or controllers it's useful to know the cost at a particular point/region in the costmap. 
We could have an Rviz tool that allows to click on a particular cell in the costmap and get its cost. We also would need to expose a service in `costmap_2d_ros` that retrieves this cost. 

#### Implementation considerations

A first attempt was done in this [PR](https://github.com/ros-navigation/navigation2/pull/4302) but not completed

**Comment by SteveMacenski** [comment]
Merging imminent in #4546
