### ISSUE TITLE
Services for `get_costmap` are advertised with same name

### ISSUE THREAD

**Issue by otamachan** [ros-navigation/navigation2#4419]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 24.04
- ROS2 Version:
  - Rolling
- Version or commit hash:
  - e5814001b8c61413d2252a742eddfdb4b37c15a1
- DDS implementation:
  - 

#### Steps to reproduce issue

```
ros2 launch ./tools/planner_benchmarking/planning_benchmark_bringup.py
```

#### Expected behavior

Each get costmap service is advertised with each name.

#### Actual behavior

All services are advertised with same name (`get_costmap`) and calling `/global_costmap/get_costmap` service returns an unexpected map.

```bash
$ ros2 service info /global_costmap/get_costmap
Type: nav2_msgs/srv/GetCostmap
Clients count: 0
Services count: 3
```
#### Additional information

It could be adverised using topic name like
```bash
/global_costmap/get_costmap
/global_costmap/get_obstacle_layer
/global_costmap/get_static_layer
```

**Comment by SteveMacenski** [comment]
Merged, thanks for finding that!
