### ISSUE TITLE
ROS1 leftovers

### ISSUE THREAD

**Issue by reinzor** [ros-navigation/navigation2#4433]
Hi there,

Just filing this issue because you might not know about some ros1 lefovers:

- https://github.com/ros-navigation/navigation2/tree/main/nav2_costmap_2d/cfg
- https://github.com/ros-navigation/navigation2/tree/main/nav2_costmap_2d/launch

I saw there were more also in the `test` dir.

Cheers :)

**Comment by SteveMacenski** [comment]
Want to open a PR? Should be easy to merge :smile:
