### ISSUE TITLE
cross-compiling ros2-humble nav2_costmap_2d  error

### ISSUE THREAD

**Issue by yuqizhi** [ros-navigation/navigation2#4445]
--- stderr: nav2_costmap_2d                                 
WARNING: Package "%s" has newlines in the description
cc1plus: error: include location "/usr/include/eigen3" is unsafe for cross-compilation [-Werror=poison-system-directories]
cc1plus: error: include location "/usr/include/eigen3" is unsafe for cross-compilation [-Werror=poison-system-directories]
cc1plus: error: include location "/usr/include/eigen3" is unsafe for cross-compilation [-Werror=poison-system-directories]
cc1plus: error: include location "/usr/include/eigen3" is unsafe for cross-compilation [-Werror=poison-system-directories]
cc1plus: error: include location "/usr/include/eigen3" is unsafe for cross-compilation [-Werror=poison-system-directories]
cc1plus: error: include location "/usr/include/eigen3" is unsafe for cross-compilation [-Werror=poison-system-directories]
cc1plus: error: include location "/usr/include/eigen3" is unsafe for cross-compilation [-Werror=poison-system-directories]
cc1plus: error: include location "/usr/include/eigen3" is unsafe for cross-compilation [-Werror=poison-system-directories]
cc1plus: error: include location "/usr/include/eigen3" is unsafe for cross-compilation [-Werror=poison-system-directories]
cc1plus: error: include location "/usr/include/eigen3" is unsafe for cross-compilation [-Werror=poison-system-directories]
cc1plus: error: include location "/usr/include/eigen3" is unsafe for cross-compilation [-Werror=poison-system-directories]
cc1plus: error: include location "/usr/include/eigen3" is unsafe for cross-compilation [-Werror=poison-system-directories]
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/nav2_costmap_2d_core.dir/build.make:79: CMakeFiles/nav2_costmap_2d_core.dir/src/array_parser.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/nav2_costmap_2d_core.dir/build.make:163: CMakeFiles/nav2_costmap_2d_core.dir/src/costmap_math.cpp.o] Error 1
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/nav2_costmap_2d_core.dir/build.make:93: CMakeFiles/nav2_costmap_2d_core.dir/src/costmap_2d.cpp.o] Error 1
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/nav2_costmap_2d_core.dir/build.make:191: CMakeFiles/nav2_costmap_2d_core.dir/src/costmap_layer.cpp.o] Error 1
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/nav2_costmap_2d_core.dir/build.make:107: CMakeFiles/nav2_costmap_2d_core.dir/src/layer.cpp.o] Error 1
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/nav2_costmap_2d_core.dir/build.make:177: CMakeFiles/nav2_costmap_2d_core.dir/src/footprint.cpp.o] Error 1
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/nav2_costmap_2d_core.dir/build.make:233: CMakeFiles/nav2_costmap_2d_core.dir/src/footprint_collision_checker.cpp.o] Error 1
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/nav2_costmap_2d_core.dir/build.make:121: CMakeFiles/nav2_costmap_2d_core.dir/src/layered_costmap.cpp.o] Error 1
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/nav2_costmap_2d_core.dir/build.make:205: CMakeFiles/nav2_costmap_2d_core.dir/src/observation_buffer.cpp.o] Error 1
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/nav2_costmap_2d_core.dir/build.make:219: CMakeFiles/nav2_costmap_2d_core.dir/src/clear_costmap_service.cpp.o] Error 1
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/nav2_costmap_2d_core.dir/build.make:149: CMakeFiles/nav2_costmap_2d_core.dir/src/costmap_2d_publisher.cpp.o] Error 1
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/nav2_costmap_2d_core.dir/build.make:135: CMakeFiles/nav2_costmap_2d_core.dir/src/costmap_2d_ros.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:152: CMakeFiles/nav2_costmap_2d_core.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

**Comment by padhupradheep** [comment]
Could you please fill the issue template properly and reopen another issue once again.

Thanks
