### ISSUE TITLE
Can't install for ROS2 Jazzy

### ISSUE THREAD

**Issue by Raedrus** [ros-navigation/navigation2#4490]
**Required Info:**

- Operating System:
  - Ubuntu 24.04 LTS
- ROS2 Version:
  - Jazzy

#### Steps to reproduce issue
```sudo apt install ros-jazzy-navigation2```

#### Expected behavior
Expect to be able to install

#### Actual behavior
E: Unable to locate package ros-jazzy-navigation2

Wasn't the jazzy version already launched or am i being too desperate?

**Comment by padhupradheep** [comment]
https://github.com/ros-navigation/navigation2/pull/4480

Will be up in the next jazzy release.
