### ISSUE TITLE
min_turning_r parameter is not applied

### ISSUE THREAD

**Issue by JJRedmond** [ros-navigation/navigation2#4509]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 24.04
- ROS2 Version:
  - Rolling
- Version or commit hash:
  - the latest
- DDS implementation:
  - Fast-RTPS

#### Steps to reproduce issue
min_turning_r parameter is not applied if a default launch file is used. The value of min_turning_r is equal to the default value, which is 0.2. The reason is located [here](https://github.com/ros-navigation/navigation2/blob/main/nav2_mppi_controller/include/nav2_mppi_controller/motion_models.hpp#L145): "AckermannConstraints" is used as a node name

**Comment by aosmw** [comment]
@iradionov  - thankyou!

Shout this from the rooftops.
