### ISSUE TITLE
Navigation and localization is showing inactive in rviz

### ISSUE THREAD

**Issue by neerja123-gupta** [ros-navigation/navigation2#4528]
Hi All,

I am using 

- Operating System:
  - Ubuntu 22.04
- ROS2 Version:
  - Humble
- DDS implementation:
  - rmw_cyclonedds_cpp

I would like to use nav2 with KMR robot, so I installed https://github.com/MortenMDahl/kmriiwa_ws_devel to run just the kuka sunrise communication and also for state publisher and then using https://github.com/ros-navigation/navigation2.git for map creation, localization and navigation. 

However, when running navigation launch it launches everything, I can see the robot , laser scans, Global costmap and Local costmap, please see below the image. However, somehow 2d pose estimate and amcl localization is not working. so whenever I try to give goal pose using 2d pose estimate robot doesn't move. Am I doing anything wrong. Any help would be highly appreciated.

#### Steps to reproduce issue
1. Cloned nav2 repo in the ros2 ws
- git clone -b humble https://github.com/ros-navigation/navigation2.git
2. Colcon build was working fine
 
cd nav2_ws
source install/local_setup.bash
export RMW_IMPLEMENTATION= rmw_cyclonedds_cpp
So I run robot state publisher and laser scanner node which is giving scans on /scan topic
ros2 launch nav2_bringup bringup_launch.py use_sim_time:=False autostart:=True map:=/path/to/my-map.yaml

and in the sceond terminal I launch rviz using
ros2 run rviz2 rviz2 -d $(ros2 pkg prefix nav2_bringup)/share/nav2_bringup/rviz/nav2_default_view.rviz

If you see in the below image in rviz, navigation and localization is inactive. And also map I have to load separately it doesn't load automatically. So basically I load it using 
ros2 run nav2_map_server map_server --ros-args -p yaml_filename:=/home/map.yaml
ros2 liefecycle set /map_server configure
ros2 liefecycle set /map_server activate

![Screenshot from 2024-06-25 11-04-49](https://github.com/ros-navigation/navigation2/assets/56900652/882a1fbf-19e7-475e-8da5-aaf694272188)

And also it gives error 
unable to start transition 1 from current state active transition is not registered.
![Screenshot from 2024-07-09 13-26-32](https://github.com/ros-navigation/navigation2/assets/56900652/4c20d92a-d36f-4d4e-ba25-293aa6745eed)
![Screenshot from 2024-07-09 13-27-01](https://github.com/ros-navigation/navigation2/assets/56900652/78cb9900-5c26-4f41-a9e8-e2293e5121b5)

Below is my params for amcl
![Screenshot from 2024-07-09 13-32-57](https://github.com/ros-navigation/navigation2/assets/56900652/dd1488b4-3414-45c9-b4e3-629b35307010)

#### Expected behavior
Navigation and localization should be in active state

**Comment by padhupradheep** [comment]
Hello @neerja123-gupta 

In the amcl config I can see that you are setting the `robot_model_type: "nav2_amcl::omnidirectional"` which is from the pre-galactic version. Please refer here to know more about the [amcl configs.](https://docs.nav2.org/configuration/packages/configuring-amcl.html) But you are not pointing your configs to the nav2_bringup, anywhere thus you don't see the error. Nav2 bringup by default uses nav2_params.yaml, if I remember it correctly. 

And also I can reproduce your error with the map_servers. 

This tracker is for reporting bugs and requesting features. This is an issue with your specific robot configuration. This question is suitable either for the [robotics stack exchange](https://robotics.stackexchange.com/) or the robot repository itself. 

I would also highly recommend you to take a peak at our wonderful [Nav2 documentation ](https://docs.nav2.org/index.html)

To help you with the nav2_bringup, please also take a look on how the [TB3 robot](https://github.com/ros-navigation/navigation2/blob/humble/nav2_bringup/launch/tb3_simulation_launch.py) is configured. 

Also the image of the logs that you have given aren't enough, it wouldn't help us to exactly pin-point the issues. For the future, it would be real nice if you can paste the logs with the help of the different formatting tools available. 

Hope this additional link helps you fix your configuration!
