### ISSUE TITLE
Docking is not available for ros humble.

### ISSUE THREAD

**Issue by rikhsitlladeveloper** [ros-navigation/navigation2#4560]
I am using ROS Humble.
OS: Ubuntu 22.04
Robot: Unitree Go2

I am implementing Nav2 for robot but nav2 humble does not have docking.
Is any way to use docking for humble?
Thanks.
@SteveMacenski

**Comment by SteveMacenski** [comment]
See https://github.com/open-navigation/opennav_docking/tree/humble - it is already released into binaries from that repository, so we'll leave it in that repository for legacy reasons. All new ROS 2 versions have it shipped with the distribution from Nav2 directly. Hope that answers your question!
