### ISSUE TITLE
Both Slack invite links may have expired

### ISSUE THREAD

**Issue by lloydchang** [ros-navigation/navigation2#4562]
**Contexts:**

—

**Slack invite link 1.** https://join.slack.com/t/navigation2/shared_invite/zt-hu52lnnq-cKYjuhTY~sEMbZXL8p9tOw

from https://github.com/ros-navigation/navigation2/blob/main/README.md

says:

> [Please visit our community Slack here](https://join.slack.com/t/navigation2/shared_invite/zt-hu52lnnq-cKYjuhTY~sEMbZXL8p9tOw) (if this link does not work, please contact maintainers to reactivate).

—

**Slack invite link 2.** https://join.slack.com/t/navigation2/shared_invite/zt-g00k4xwx-~ABwlU1rwHU96OGihC0ESA

from https://docs.nav2.org/about/index.html#contact

says:

> Check out the Navigation 2 [Slack](https://join.slack.com/t/navigation2/shared_invite/zt-g00k4xwx-~ABwlU1rwHU96OGihC0ESA) community.
https://docs.nav2.org/about/index.html#contact

—

**Both Slack invite links:**

1. https://join.slack.com/t/navigation2/shared_invite/zt-hu52lnnq-cKYjuhTY~sEMbZXL8p9tOw

and

2. https://join.slack.com/t/navigation2/shared_invite/zt-g00k4xwx-~ABwlU1rwHU96OGihC0ESA

say:

> The email address must match one of the domains listed below. Please try another email.

> You can use any account with the domain:
> roverrobotics.com
> digilabs.io
> Don’t have an email address from one of those domains?
> Contact the workspace administrator at Nav2 for an invitation.

**Comment by SteveMacenski** [comment]
Updated both, thanks!
