### ISSUE TITLE
Model State Initialization

### ISSUE THREAD

**Issue by KoushikRaghav** [ros-navigation/navigation2#4581]
Hi, I'm trying to understand mppi controller's constraint critic logic. I would like to know where `critics_data.state.vx`,`critics_data.state.vy`,`critics_data.state.wz` are getting initialized. I could see a matrix of data being initialized. When looked into optimizer.cpp, all the member variables of state.hpp are getting initialized (like robotpose, velocity, fail_flag). Can anyone help me to understand this? I wanted to add a new constraint to restrict the yaw motion of the robot

**Comment by SteveMacenski** [comment]
Ask on robot stack exchange, this is not the correct place for Q&A
