### ISSUE TITLE
The callback function of subscriber is not called while navigation is in progress.

### ISSUE THREAD

**Issue by atinfinity** [ros-navigation/navigation2#4619]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22.04
- ROS2 Version:
  - Humble binaries
- Version
  - ros-humble-navigation2  1.1.15-1jammy.20240627.172212
  - ros-humble-nav2-amcl    1.1.15-1jammy.20240530.085224
  - ros-humble-nav2-behavior-tree   1.1.15-1jammy.20240626.151221
  - ros-humble-nav2-behaviors       1.1.15-1jammy.20240627.171322
  - ros-humble-nav2-bringup 1.1.15-1jammy.20240627.172242
  - ros-humble-nav2-bt-navigator    1.1.15-1jammy.20240627.171011
  - ros-humble-nav2-collision-monitor       1.1.15-1jammy.20240627.170404
  - ros-humble-nav2-common  1.1.15-1jammy.20240524.012550
  - ros-humble-nav2-constrained-smoother    1.1.15-1jammy.20240627.171203
  - ros-humble-nav2-controller      1.1.15-1jammy.20240627.171012
  - ros-humble-nav2-core    1.1.15-1jammy.20240627.170419
  - ros-humble-nav2-costmap-2d      1.1.15-1jammy.20240627.164242
  - ros-humble-nav2-dwb-controller  1.1.15-1jammy.20240627.171715
  - ros-humble-nav2-lifecycle-manager       1.1.15-1jammy.20240627.145323
  - ros-humble-nav2-map-server      1.1.15-1jammy.20240530.085325
  - ros-humble-nav2-mppi-controller 1.1.15-1jammy.20240627.170630
  - ros-humble-nav2-msgs    1.1.15-1jammy.20240524.013914
  - ros-humble-nav2-navfn-planner   1.1.15-1jammy.20240627.170727
  - ros-humble-nav2-planner 1.1.15-1jammy.20240627.170730
  - ros-humble-nav2-regulated-pure-pursuit-controller       1.1.15-1jammy.20240627.170814
  - ros-humble-nav2-rotation-shim-controller        1.1.15-1jammy.20240627.171721
  - ros-humble-nav2-rviz-plugins    1.1.15-1jammy.20240627.164256
  - ros-humble-nav2-simple-commander        1.1.15-1jammy.20240524.014726
  - ros-humble-nav2-smac-planner    1.1.15-1jammy.20240627.170819
  - ros-humble-nav2-smoother        1.1.15-1jammy.20240627.171035
  - ros-humble-nav2-theta-star-planner      1.1.15-1jammy.20240627.170840
  - ros-humble-nav2-util    1.1.15-1jammy.20240530.084407
  - ros-humble-nav2-velocity-smoother       1.1.15-1jammy.20240530.094814
  - ros-humble-nav2-voxel-grid      1.1.15-1jammy.20240524.013953
  - ros-humble-nav2-waypoint-follower       1.1.15-1jammy.20240627.171044
- DDS implementation:
  - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

#### Steps to reproduce issue

I used <https://github.com/atinfinity/megarover_samples_ros2>.

```shell
sudo apt install ros-humble-rmw-cyclonedds-cpp
export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
mkdir -p ~/dev_ws/src
cd ~/dev_ws/src
git clone https://github.com/atinfinity/megarover_samples_ros2.git
cd ..
rosdep install -y -i --from-paths src/megarover_samples_ros2
colcon build --symlink-install
source ~/dev_ws/install/setup.bash
```

And, I launched Gazebo and navigation2.

```shell
ros2 launch megarover_samples_ros2 vmegarover_with_sample_world.launch.py
ros2 launch megarover_samples_ros2 vmegarover_navigation.launch.py
```

I launched the following node using BasicNavigator(<https://docs.nav2.org/commander_api/index.html>).

```python
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import PoseStamped
from std_msgs.msg import Empty
from nav2_simple_commander.robot_navigator import BasicNavigator


class ExampleNavigationNode(Node):

    def __init__(self):
        super().__init__('example_navigation')
        self.navigation_cancel_subscriber = self.create_subscription(
            Empty,
            '/dummy',
            self.sub_dummy_callback,
            10)

        self.goal_pose = PoseStamped()
        self.goal_pose.header.frame_id = 'map'
        self.goal_pose.header.stamp = self.get_clock().now().to_msg()
        self.goal_pose.pose.position.x = 2.0
        self.goal_pose.pose.position.y = 0.0
        self.goal_pose.pose.orientation.w = 1.0
        self.goal_pose.pose.orientation.z = 0.0

        self.navigator = BasicNavigator()
        self.navigator.waitUntilNav2Active()
        self.navigator.goToPose(self.goal_pose)
        while not self.navigator.isTaskComplete():
            feedback = self.navigator.getFeedback()
        result = self.navigator.getResult()
        self.get_logger().info(f"result = {result}")

    def sub_dummy_callback(self, msg):
        self.get_logger().info("sub_dummy_callback")


def main():
    rclpy.init()
    node = ExampleNavigationNode()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()


if __name__ == "__main__":
    main()
```

After the starting of navigation, I executed the following command.

```bash
ros2 topic pub --once /dummy std_msgs/msg/Empty "{}"
```

#### Expected behavior

I expected that the following message is displayed when I publish `/dummy` topic.

```bash
[example_navigation]: sub_dummy_callback
```

#### Actual behavior

The `sub_dummy_callback()` is not called while navigation is in progress.

**Comment by padhupradheep** [comment]
Hey, 

The `robotNavigator` by itself has a node `base_navigator` within it. Therefore, you need to checkout the rcply executors which could allow your rclpy nodes run in different threads. 

Check the docs about the executors: https://docs.ros.org/en/humble/Concepts/Intermediate/About-Executors.html
Check the rclpy api: https://docs.ros2.org/foxy/api/rclpy/api/execution_and_callbacks.html#module-rclpy.executors

Also for your kind information, this tracker is for mostly reporting bugs and requesting features. Feel free to post on https://robotics.stackexchange.com/ if you have questions related to your code.
