### ISSUE TITLE
Missing nav2_namespaced_view.rviz referenced in launch files

### ISSUE THREAD

**Issue by k12onoss** [ros-navigation/navigation2#4623]
Both the `cloned_multi_tb3_simulation_launch.py` and `unique_multi_tb3_simulation_launch.py` reference a `nav2_namespaced_view.rviz` as a default rviz config file, but it doesn't exist anymore. Is there a reason for it's removal?

**Comment by SteveMacenski** [comment]
This is a good point! It looks like it was removed in an incorrect merge conflict resolution when readding in the multirobot launch files. I've readded it https://github.com/ros-navigation/navigation2/pull/4625 and will backport to Jazzy immediately.

Thanks for the report!
