### ISSUE TITLE
Restore exported BT util test files after cmake revamp

### ISSUE THREAD

**Issue by aosmw** [ros-navigation/navigation2#4652]
## Bug report

With the cmake revamp the intent of https://github.com/ros-navigation/navigation2/pull/3372 has been lost.
In order to have users write tests for bt nodes in order modules, the test utility files must be installed/exported.

#### Expected behavior
```
rm -fr install/nav2_behavior_tree
colcon build --packages-select nav2_behavior_tree
find install -name test_service.hpp
install/nav2_behavior_tree/include/nav2_behavior_tree/nav2_behavior_tree/test/utils/test_service.hpp
```

#### Actual behavior
test_service.hpp not found.

@clalancette possible fix... is this enough?
```
--- a/src/navigation2/nav2_behavior_tree/CMakeLists.txt
+++ b/src/navigation2/nav2_behavior_tree/CMakeLists.txt
@@ -256,6 +256,10 @@ install(DIRECTORY include/
   DESTINATION include/${PROJECT_NAME}
 )
 
+install(DIRECTORY test/utils/
+  DESTINATION include/${PROJECT_NAME}/nav2_behavior_tree/test/utils
```

**Comment by SteveMacenski** [comment]
If that fixes the problem for you, it seems to me to be sufficient on face value. Please open a PR!
