### ISSUE TITLE
I got this error [component_container_isolated-2] [ERROR] [1725418332.608375481] [transformPoseInTargetFrame]: Failed to transform from  to base_link

### ISSUE THREAD

**Issue by fllay** [ros-navigation/navigation2#4660]
When I am using slam async in slam toolbox, I got this error 
```
[component_container_isolated-2] [ERROR] [1725418332.608375481] [transformPoseInTargetFrame]: Failed to transform from  to base_link
```
However, the robot seems to navigate just fine. From the error message `Failed to transform from  to base_link` , it seems that it tries to transform from blank frame to base_link. Any idea, where can I config that?

**Comment by padhupradheep** [comment]
Hey, this is not the relevant repo to post this. 

For that matter of fact your question would really fit in https://robotics.stackexchange.com/
