### ISSUE TITLE
Potential endless loop if a costmap layer does not update.

### ISSUE THREAD

**Issue by tgreier** [ros-navigation/navigation2#4672]
Operating System: Ubuntu
    ROS2 Version: humble and main branches
    Version or commit hash: N/A
    DDS implementation: N/A

**Expected behavior**
If a costmap does not update, then the planner server action should fail and the planner should output an error diagnostic.

**Actual behavior**

PlannerServer::waitForCostmap() has no breakout timeout. Therefore, the planner server remains in loop if a costmap layer does not update, and there is no indication of why the planner server does not respond or updates its action request.
This loop should have a breakout condition with failure return and response.

https://github.com/ros-navigation/navigation2/blob/7eb47d84012dd9e25988ce5c9c269280e6ee3dd1/nav2_planner/src/planner_server.cpp#L282

**Comment by SteveMacenski** [comment]
Fair point, @tgreier please review https://github.com/ros-navigation/navigation2/pull/4673 and let me know if this solves your concern

**Comment by SteveMacenski** [comment]
I also added the controller server as well
