### ISSUE TITLE
Could not find example_route.py in nav2_simple_commander

### ISSUE THREAD

**Issue by atinfinity** [ros-navigation/navigation2#4683]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22.04
- ROS2 Version:
  - Humble binaries
- Version
  - ros-humble-navigation2  1.1.15-1jammy.20240627.172212
  - ros-humble-nav2-amcl    1.1.15-1jammy.20240530.085224
  - ros-humble-nav2-behavior-tree   1.1.15-1jammy.20240626.151221
  - ros-humble-nav2-behaviors       1.1.15-1jammy.20240627.171322
  - ros-humble-nav2-bringup 1.1.15-1jammy.20240627.172242
  - ros-humble-nav2-bt-navigator    1.1.15-1jammy.20240627.171011
  - ros-humble-nav2-collision-monitor       1.1.15-1jammy.20240627.170404
  - ros-humble-nav2-common  1.1.15-1jammy.20240524.012550
  - ros-humble-nav2-constrained-smoother    1.1.15-1jammy.20240627.171203
  - ros-humble-nav2-controller      1.1.15-1jammy.20240627.171012
  - ros-humble-nav2-core    1.1.15-1jammy.20240627.170419
  - ros-humble-nav2-costmap-2d      1.1.15-1jammy.20240627.164242
  - ros-humble-nav2-dwb-controller  1.1.15-1jammy.20240627.171715
  - ros-humble-nav2-lifecycle-manager       1.1.15-1jammy.20240627.145323
  - ros-humble-nav2-map-server      1.1.15-1jammy.20240530.085325
  - ros-humble-nav2-mppi-controller 1.1.15-1jammy.20240627.170630
  - ros-humble-nav2-msgs    1.1.15-1jammy.20240524.013914
  - ros-humble-nav2-navfn-planner   1.1.15-1jammy.20240627.170727
  - ros-humble-nav2-planner 1.1.15-1jammy.20240627.170730
  - ros-humble-nav2-regulated-pure-pursuit-controller       1.1.15-1jammy.20240627.170814
  - ros-humble-nav2-rotation-shim-controller        1.1.15-1jammy.20240627.171721
  - ros-humble-nav2-rviz-plugins    1.1.15-1jammy.20240627.164256
  - ros-humble-nav2-simple-commander        1.1.15-1jammy.20240524.014726
  - ros-humble-nav2-smac-planner    1.1.15-1jammy.20240627.170819
  - ros-humble-nav2-smoother        1.1.15-1jammy.20240627.171035
  - ros-humble-nav2-theta-star-planner      1.1.15-1jammy.20240627.170840
  - ros-humble-nav2-util    1.1.15-1jammy.20240530.084407
  - ros-humble-nav2-velocity-smoother       1.1.15-1jammy.20240530.094814
  - ros-humble-nav2-voxel-grid      1.1.15-1jammy.20240524.013953
  - ros-humble-nav2-waypoint-follower       1.1.15-1jammy.20240627.171044
- DDS implementation:
  - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

### Problem

I read <https://docs.nav2.org/commander_api/index.html> to use Simple Commander API.
In this document, there is the following description.

> - `example_route.py` - Demonstrates the Route server capabilities of the navigator.

But, there is no this script in <https://github.com/ros-navigation/navigation2/tree/main/nav2_simple_commander/nav2_simple_commander>.

I think that this is related to <https://github.com/ros-navigation/navigation2/issues/4550>.

**Comment by SteveMacenski** [comment]
Thanks, and completed in https://github.com/ros-navigation/docs.nav2.org/commit/8bb00f0dbe2714f762901ccb52d3b910d911d1d6!
