### ISSUE TITLE
Enhancement for Rotation Shim Controller

### ISSUE THREAD

**Issue by sandeepdutta** [ros-navigation/navigation2#4688]
## Feature Rquest

**Required Info:**

- Operating System:
  - All
- ROS2 Version:
  - Humble
- Version or commit hash:
  - humble
- DDS implementation:
  - Cyclone DDS

#### Feature request
 Additional parameter in Rotation Shim to control disengage angle

#### Feature description 
In congested spaces, we want the Rotation Shim Controller to engage when the angular divergence from the 
path is high (typically at the start of navigate to pose) and disengage when the pose is aligned very closely with the
path. The Shim currently has only one parameter to control when it engages and disengages  , setting this parameter
to  low value (say 10 degrees) will cause the Shim to engage on small turns causing jerky movement, setting this value
high will cause it to disengage when the  angular distance is high.

This proposal is to add an additional parameter , "angular_disengage_threshold", this will allow the Shim to
engage at high angular divergence and disengage at lower angular divergence.

#### Implementation considerations
 An implementation of this can be found at https://github.com/sandeepdutta/navigation2/blob/humble/nav2_rotation_shim_controller/src/nav2_rotation_shim_controller.cpp

Thank you
Sandeep

**Comment by SteveMacenski** [comment]
This was merged!
