### ISSUE TITLE
BUG:two close right-anlges in global path triggers robot stop

### ISSUE THREAD

**Issue by cliffe10086** [ros-navigation/navigation2#4718]
## Bug report

**Required Info:**

- Operating System:Ubuntu 22.04
  - 
- ROS2 Version:humble
  - 
- Version or commit hash:f79de33c3c192cd66377dc9538bdcbc3597b7f66
  - 
- DDS implementation:default
  - 

#### Steps to reproduce issue

```use cmd from nav2 website 
export TURTLEBOT3_MODEL=waffle
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/opt/ros/humble/share/turtlebot3_gazebo/models
ros2 launch nav2_bringup tb3_simulation_launch.py headless:=False

then in gazebo ignition, put two walls to filll between tow polls like (.-.-.)
robort is below the wall in the middle , goal is above the wall in the middle.
     G(oal)
.---------.
     R(obort)
```

#### Expected behavior
turn tow right-angle corners and arrive
#### Actual behavior
stop at origin spot
#### Additional information
[录屏 2024年10月10日 10时34分59秒.webm](https://github.com/user-attachments/assets/3ef01ba6-034d-494d-bcac-d2c8128faee3)
none，my english is poor ,sorry if make troubles

**Comment by SteveMacenski** [comment]
I don’t understand what you mean. Can you describe this in more detail with some image if necessary?

**Comment by cliffe10086** [comment]
i have a video submitted above.here are two more image.in the first ,when global path has two right-angle corner,robort will stop.in second is a provided gazebo map with two small change(added two walls).
![截图 2024-10-11 10-18-17](https://github.com/user-attachments/assets/98f96f6a-b23e-4676-9451-d87b8e7cd235)
![截图 2024-10-11 10-17-35](https://github.com/user-attachments/assets/019d78da-4ebe-4427-9787-d135e8f24c6b)

**Comment by SteveMacenski** [comment]
Have you made an attempt to tune the controller? Which are you using and what are its parameters?

**Comment by SteveMacenski** [comment]
Closing due to lack of response
