### ISSUE TITLE
Can I use jazzy branch code in ROS 2 humble?

### ISSUE THREAD

**Issue by mqjinwon** [ros-navigation/navigation2#4728]
I want to build the Jazzy branch of the Navigation2 repository on Ubuntu 22.04 with ROS 2 Humble, but I encountered several errors during the build process. Has anyone successfully built this setup? If so, could you share your experience or offer some guidance?

### Bug Report

**Required Info:**

- **Operating System:**
  - Ubuntu 22.04
- **ROS2 Version:**
  - ROS2 Humble
- **Version or Commit Hash:**
  - Jazzy branch of Navigation2
- **DDS Implementation:**
  - Default DDS

### Steps to Reproduce:

1. Cloned the `jazzy` branch from the Navigation2 repository:
 ```bash
 git clone --branch jazzy https://github.com/ros-planning/navigation2.git
 ```

2. Installed dependencies and workspace setup:
  ```bash
  rosdep install --from-paths src --ignore-src -r -y
  colcon build --symlink-install
  ```

And I got a lot of errors when the project building.
If you’ve also faced this problem and managed to resolve it, please share your solution.

**Comment by SteveMacenski** [comment]
No, each branch targets a specific distribution. If you’re using ROS 2 Humble, you should use the Humble branch. ROS 2 and other API changes have occurred which makes it expected that you cannot compile the Jazzy branch on Humble (and vise versa). Code changes and reverting API changes would need to be done
