### ISSUE TITLE
Request for resources on alternative navigation packages to Nav2 in ROS 2

### ISSUE THREAD

**Issue by alifazeli00** [ros-navigation/navigation2#4762]
In addition to the Nav2 package for navigation in ROS 2, what other packages can be used? Are there any references or resources available to explore and compare these packages and their features?

**Comment by SteveMacenski** [comment]
I am not aware of any of note for industrial / commercial use that are open source or may be used without paying commercial licensing.

**Comment by mikeferguson** [comment]
You could always roll your own. I hear some crazy people like Rust as a medium for rewriting software...
