### ISSUE TITLE
[feature request]: Add parameter to the DriveOnHeading and BackUp actions to disable collision checking

### ISSUE THREAD

**Issue by david-wb** [ros-navigation/navigation2#4783]
#### Feature description

The title is self-explanatory, but the purpose of this feature is that, in some cases we might want to advance the robot even in the presence of obstacles, e.g. to intentionally push an obstacle. 

Related to [this](https://robotics.stackexchange.com/questions/113902/how-to-choose-controller-when-using-nav2s-driveonheading-commander-api) Robotics StackExchange question.

#### Implementation considerations

I think the feature can be implemented quite simply by adding a new boolean param to the action messages and using the param inside of the DriveOnHeading implementation to short-circuit collision checking when the param is true. 

#### Ownership
I intend to take ownership of this ticket and produce a PR within 1-2 days.

**Comment by SteveMacenski** [comment]
Thanks! I look forward to it :-)
