### ISSUE TITLE
MPPI How to set acceleration param

### ISSUE THREAD

**Issue by debanik123** [ros-navigation/navigation2#4787]
How to set acceleration parameters in MPPI? The documentation mentions parameters like ax_max and ax_min, but these parameters don't actually exist in reality. Why is that?                                                                                                                                ros2 param get /controller_server FollowPath.
FollowPath.ConstraintCritic.cost_power
FollowPath.ConstraintCritic.cost_weight
FollowPath.ConstraintCritic.enabled
FollowPath.CostCritic.collision_cost
FollowPath.CostCritic.consider_footprint
FollowPath.CostCritic.cost_power
FollowPath.CostCritic.cost_weight
FollowPath.CostCritic.critical_cost
FollowPath.CostCritic.enabled
FollowPath.CostCritic.inflation_layer_name
FollowPath.CostCritic.near_goal_distance
FollowPath.GoalAngleCritic.cost_power
FollowPath.GoalAngleCritic.cost_weight
FollowPath.GoalAngleCritic.enabled
FollowPath.GoalAngleCritic.threshold_to_consider
FollowPath.GoalCritic.cost_power
FollowPath.GoalCritic.cost_weight
FollowPath.GoalCritic.enabled
FollowPath.GoalCritic.threshold_to_consider
FollowPath.PathAlignCritic.cost_power
FollowPath.PathAlignCritic.cost_weight
FollowPath.PathAlignCritic.enabled
FollowPath.PathAlignCritic.max_path_occupancy_ratio
FollowPath.PathAlignCritic.offset_from_furthest
FollowPath.PathAlignCritic.trajectory_point_step
FollowPath.PathAlignCritic.use_path_orientations
FollowPath.PathAngleCritic.cost_power
FollowPath.PathAngleCritic.cost_weight
FollowPath.PathAngleCritic.enabled
FollowPath.PathAngleCritic.forward_preference
FollowPath.PathAngleCritic.max_angle_to_furthest
FollowPath.PathAngleCritic.offset_from_furthest
FollowPath.PathAngleCritic.threshold_to_consider
FollowPath.PathFollowCritic.cost_power
FollowPath.PathFollowCritic.cost_weight
FollowPath.PathFollowCritic.enabled
FollowPath.PathFollowCritic.offset_from_furthest
FollowPath.PathFollowCritic.threshold_to_consider
FollowPath.PreferForwardCritic.cost_power
FollowPath.PreferForwardCritic.cost_weight
FollowPath.PreferForwardCritic.enabled
FollowPath.PreferForwardCritic.threshold_to_consider
FollowPath.TrajectoryVisualizer.time_step
FollowPath.TrajectoryVisualizer.trajectory_step
FollowPath.angular_dist_threshold
FollowPath.batch_size
FollowPath.critics
FollowPath.enforce_path_inversion
FollowPath.forward_sampling_distance
FollowPath.gamma
FollowPath.iteration_count
FollowPath.max_angular_accel
FollowPath.max_robot_pose_search_dist
FollowPath.model_dt
FollowPath.motion_model
FollowPath.plugin
FollowPath.primary_controller
FollowPath.prune_distance
FollowPath.regenerate_noises
FollowPath.reset_period
FollowPath.retry_attempt_limit
FollowPath.rotate_to_goal_heading
FollowPath.rotate_to_heading_angular_vel
FollowPath.simulate_ahead_time
FollowPath.temperature
FollowPath.time_steps
FollowPath.transform_tolerance
FollowPath.visualize
FollowPath.vx_max
FollowPath.vx_min
FollowPath.vx_std
FollowPath.vy_max
FollowPath.vy_std
FollowPath.wz_max
FollowPath.wz_std

**Comment by mini-1235** [comment]
The ax_min and max parameters are added in the commit 9367c62, the version you are using might not have this update
