### ISSUE TITLE
Shouldn't the default value of unknown_cost_value be -1?

### ISSUE THREAD

**Issue by tonynajjar** [ros-navigation/navigation2#4788]
The [default value](https://github.com/angsa-robotics/navigation2/blob/58dc8bbc66fbbd5a111a1fa4ac57ca04a3d10201/nav2_costmap_2d/src/costmap_2d_ros.cpp#L125) of `unknown_cost_value` is 255, I guess after `NO_INFORMATION`. However the `unknown_cost_value` parameter is used in the static_layer in the context of OccupancyGrids [where the value for `UNKNOWN` is -1](https://github.com/ros2/common_interfaces/blob/c0c0bc57f958eb54a142446f0c2a475754367eee/nav_msgs/msg/OccupancyGrid.msg#L12).

**Comment by SteveMacenski** [comment]
The max value of an unsigned char is `255`, so if you set to `-1`, it wraps around to 255.  These are equivalent statements :-)
