### ISSUE TITLE
WHY the humble version of navigation2 is missing controller_exceptions.hpp in the nav2_core/inludes folder ?

### ISSUE THREAD

**Issue by G-Apple1** [ros-navigation/navigation2#4814]
## Bug report

**Required Info:**

- Operating System: ubuntu22.04
  - 
- ROS2 Version: humble
  - 
- Version or commit hash: humble
  - 
- DDS implementation:
  - 

#### Steps to reproduce issue

```
The humble version of navigation2 is missing controller_exceptions.hpp in the nav2_core/inlude folder. Why ?
```
![image](https://github.com/user-attachments/assets/6f3b4f3a-f524-4f96-85e5-6e1e52f224f4)

**Comment by mini-1235** [comment]
The latest humble release is 1.1.17, which does not have controller exception implemented, you should use the correct branch code

**Comment by SteveMacenski** [comment]
Precisely. Changes are made over the evolution of the project and not all changes can be backported to older distributions using best-practices ABI/API stability policy requirement s
